
package com.buzonfiscal.timbradocfdi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.buzonfiscal.ns.xsd.bf.timbradocfd.RequestTimbradoCFDType;
import mx.gob.sat.timbrefiscaldigital.TimbreFiscalDigital;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TimbradoCFDI", targetNamespace = "http://www.buzonfiscal.com/TimbradoCFDI/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.buzonfiscal.ns.referenceid.v1.ObjectFactory.class,
    com.buzonfiscal.ns.xsd.bf.timbradocfd.ObjectFactory.class,
    mx.gob.sat.timbrefiscaldigital.ObjectFactory.class,
    com.buzonfiscal.ns.xsd.bf.requesttimbracfdi.ObjectFactory.class,
    com.buzonfiscal.timbradocfdi.ObjectFactory.class
})
public interface TimbradoCFDI {


    /**
     * 
     * @param request
     * @return
     *     returns mx.gob.sat.timbrefiscaldigital.TimbreFiscalDigital
     */
    @WebMethod(action = "https://demotf.buzonfiscal.com/timbrado")
    @WebResult(name = "TimbreFiscalDigital", targetNamespace = "http://www.sat.gob.mx/TimbreFiscalDigital", partName = "response")
    public TimbreFiscalDigital timbradoCFD(
        @WebParam(name = "RequestTimbradoCFD", targetNamespace = "http://www.buzonfiscal.com/ns/xsd/bf/TimbradoCFD", partName = "request")
        RequestTimbradoCFDType request);

}
